### ISSUE TITLE
When I try to import npz file , I am getting following errors (I tried in blender 2.83, 2.92,2.93 with release Quick Mocap v0.3.3.2 Bug Fix): 

### ISSUE THREAD

**Issue by Crackpack** [vltmedia/QuickMocap-BlenderAddon#3]
Processing: E:/AI/ROMP/ROMP-master/demo/sample_video2_results/sample_video2_results/sample_video2_results.npz
Traceback (most recent call last):
  File "C:\Users\Sanjay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\QuickMocap\operators\quickmocap_Op_ImportNumpyMocap.py", line 31, in execute
    rotate_neg=quickmocap_tool.rotate_neg,
  File "C:\Users\Sanjay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\QuickMocap\helpers\smpl_import.py", line 250, in process_poses
    self.poses[frame_id] = data['{}'.format(frame_id)][0]['pose']
KeyError: '0'

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\Sanjay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\QuickMocap\operators\quickmocap_Op_ImportNumpyMocap.py", line 31, in execute
    rotate_neg=quickmocap_tool.rotate_neg,
  File "C:\Users\Sanjay\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\QuickMocap\helpers\smpl_import.py", line 250, in process_poses
    self.poses[frame_id] = data['{}'.format(frame_id)][0]['pose']
KeyError: '0'

location: <unknown location>:-1

I am using npz values from sample video 2 of ROMP

**Comment by vltmedia** [comment]
Can you link me the .npz file and we can test it?
It seems the SMPL importer is having trouble with the .npz file you're feeding it.

**Comment by sascharo** [comment]
Has this been fixed?
